---
name: Report an issue in yi-hack_ha_integration code
description: >
  This is for issues with  yi-hack_ha_integration code only. If you have a
  question or a feature request, use Discussions.
body:
  - type: textarea
    id: issue_description
    validations:
      required: true
    attributes:
      label: The issue
      description: >
        Describe the issue you are experiencing. Describe what you did, and
        what happened.

  - type: input
    id: camera_name
    validations:
      required: true
    attributes:
      label: Which camera are you using?
      description: >
        Describe camera name. Include the product name of the camera, and
        first 4 letters of serial number, such as `Yi Dome Guard QFUS`.

  - type: checkboxes
    id: targets
    validations:
      required: true
    attributes:
      label: Which target of `yi-hack` are you using on the camera?
      description: >
        Describe `yi-hack` target on your camera.
      options:
        - label: `yi-hack-MStar`
        - label: `yi-hack-Allwinner`
        - label: `yi-hack-Allwinner-v2`
        - label: ``yi-hack-v5`
        - label: `sonoff-hack`

  - type: input
    id: yi_hack_version
    validations:
      required: true
    attributes:
      label: Which version of `yi-hack` are you using on the camera?
      description: >
        Describe `yi-hack` version on your camera. The version can be either
        release version, or git hash.

  - type: input
    id: yi_hach_ha_integration_version
    validations:
      required: true
    attributes:
      label: Which version of ` yi-hack_ha_integration` are you using?
      description: >
        Describe ` yi-hack_ha_integration` version on Home Assistant. The
        version can be either release version, or git hash.

  - type: input
    id: hass_version
    validations:
      required: true
    attributes:
      label: Which version of Home Assistant are you using?
      description: >
        Describe Home Assistant version.

  - type: input
    id: python_version
    validations:
      required: true
    attributes:
      label: Which version of `python` are you using?
      description: >
        Describe `python` version.

  - type: textarea
    id: log
    attributes:
      label: Anything in the logs that might be useful for us?
      render: console
      description: >
        For example, error message, or back traces. Paste raw log output
        here. The log will be formatted into `console` codeblock.

  - type: textarea
    id: extra_info
    attributes:
      label: Additional information or context
      description: >
        If you have any additional information and/or context for us, use the
        field below.

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm and check the box below.
      options:
        - label: This report is not a question nor a feature request.
          required: true
